/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codevitaliy.mavenproject1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author codevitaliy
 */
public class Practica1 extends javax.swing.JFrame {
    
    String finalMessage,nombreVehiculo,nombreModelo,yearVehiculo,tipoCombustible,
            tipoVehiculo,tipoAdd,mensajeMenu;
    
   
    public Practica1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextModelo = new javax.swing.JTextField();
        jTextYear = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jCheckBoxTipoCoche = new javax.swing.JCheckBox();
        jCheckBoxTipoMoto = new javax.swing.JCheckBox();
        jCheckBoxTipoCamion = new javax.swing.JCheckBox();
        jLabelCombustible = new javax.swing.JLabel();
        jLabelAdd = new javax.swing.JLabel();
        jCheckBoxAddRemolque = new javax.swing.JCheckBox();
        jCheckBoxAddCapota = new javax.swing.JCheckBox();
        jCheckBoxAddSidecar = new javax.swing.JCheckBox();
        jRadioButtonGasGasolina = new javax.swing.JRadioButton();
        jRadioButtonGasDiesel = new javax.swing.JRadioButton();
        jRadioButtonGasElectrico = new javax.swing.JRadioButton();
        jComboBoxColors = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMarcaModelo = new javax.swing.JTable();
        jButtonStart = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonAddVehiculo = new javax.swing.JButton();
        jButtonRemoveVehiculo = new javax.swing.JButton();
        jMenuBarCoches = new javax.swing.JMenuBar();
        jMenuCoche = new javax.swing.JMenu();
        jMenuCocheMensaje = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuMoto = new javax.swing.JMenu();
        jMenuMotoMensaje = new javax.swing.JMenu();
        jMenuCamion = new javax.swing.JMenu();
        jMenuCamionMensaje = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(246, 212, 204));
        setEnabled(false);
        setForeground(java.awt.Color.orange);

        jLabelMarca.setText("MARCA:");
        jLabelMarca.setToolTipText("");
        jLabelMarca.setName(""); // NOI18N

        jLabelModelo.setText("MODELO:");

        jLabelYear.setText("AÑO:");

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextModeloActionPerformed(evt);
            }
        });

        jTextYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextYearActionPerformed(evt);
            }
        });

        jLabelTipo.setText("TIPO:");

        jCheckBoxTipoCoche.setText("Coche");
        jCheckBoxTipoCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTipoCocheActionPerformed(evt);
            }
        });

        jCheckBoxTipoMoto.setText("Moto");
        jCheckBoxTipoMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTipoMotoActionPerformed(evt);
            }
        });

        jCheckBoxTipoCamion.setText("Camion");
        jCheckBoxTipoCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTipoCamionActionPerformed(evt);
            }
        });

        jLabelCombustible.setText("COMBUSTIBLE:");

        jLabelAdd.setText("ADD:");

        jCheckBoxAddRemolque.setText("Remolque");
        jCheckBoxAddRemolque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAddRemolqueActionPerformed(evt);
            }
        });

        jCheckBoxAddCapota.setText("Capota");
        jCheckBoxAddCapota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAddCapotaActionPerformed(evt);
            }
        });

        jCheckBoxAddSidecar.setText("Sidecar");
        jCheckBoxAddSidecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAddSidecarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonGasGasolina);
        jRadioButtonGasGasolina.setText("Gasolina");
        jRadioButtonGasGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGasGasolinaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonGasDiesel);
        jRadioButtonGasDiesel.setText("Diesel");
        jRadioButtonGasDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGasDieselActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonGasElectrico);
        jRadioButtonGasElectrico.setText("Electric");
        jRadioButtonGasElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGasElectricoActionPerformed(evt);
            }
        });

        jComboBoxColors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plateado", "Azul", "Rojo", "Blanco" }));
        jComboBoxColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColorsActionPerformed(evt);
            }
        });

        jTableMarcaModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MARCA", "MODELO"
            }
        ));
        jTableMarcaModelo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableMarcaModelo);

        jButtonStart.setText("START");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonAddVehiculo.setText("Add");
        jButtonAddVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVehiculoActionPerformed(evt);
            }
        });

        jButtonRemoveVehiculo.setText("Remove");
        jButtonRemoveVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveVehiculoActionPerformed(evt);
            }
        });

        jMenuCoche.setText("Coche");
        jMenuCoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCocheMouseClicked(evt);
            }
        });
        jMenuCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCocheActionPerformed(evt);
            }
        });

        jMenuCocheMensaje.setText("Mensaje");
        jMenuCocheMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCocheMensajeMouseClicked(evt);
            }
        });
        jMenuCoche.add(jMenuCocheMensaje);

        jMenu1.setText("jMenu1");
        jMenuCoche.add(jMenu1);

        jMenu2.setText("jMenu2");
        jMenuCoche.add(jMenu2);

        jMenuBarCoches.add(jMenuCoche);

        jMenuMoto.setText("Moto");
        jMenuMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMotoMouseClicked(evt);
            }
        });

        jMenuMotoMensaje.setText("Mensaje");
        jMenuMotoMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMotoMensajeMouseClicked(evt);
            }
        });
        jMenuMoto.add(jMenuMotoMensaje);

        jMenuBarCoches.add(jMenuMoto);

        jMenuCamion.setText("Camion");
        jMenuCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCamionMouseClicked(evt);
            }
        });

        jMenuCamionMensaje.setText("Mensaje");
        jMenuCamionMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCamionMensajeMouseClicked(evt);
            }
        });
        jMenuCamion.add(jMenuCamionMensaje);

        jMenuBarCoches.add(jMenuCamion);

        setJMenuBar(jMenuBarCoches);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCombustible)
                    .addComponent(jLabelTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxTipoMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAddCapota, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBoxTipoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxAddRemolque, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTipoCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonGasGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxAddSidecar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxColors, 0, 85, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonGasElectrico, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonGasDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAddVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoveVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarca)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelModelo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelYear)
                            .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipo)
                            .addComponent(jCheckBoxTipoCoche)
                            .addComponent(jLabelAdd)
                            .addComponent(jCheckBoxAddRemolque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxTipoMoto)
                            .addComponent(jCheckBoxAddCapota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxTipoCamion)
                            .addComponent(jCheckBoxAddSidecar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCombustible)
                            .addComponent(jRadioButtonGasGasolina)
                            .addComponent(jComboBoxColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonGasDiesel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonGasElectrico))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddVehiculo)
                        .addComponent(jButtonRemoveVehiculo)))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
        nombreVehiculo = jTextNombre.getText();
        
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jCheckBoxTipoCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTipoCamionActionPerformed
        // TODO add your handling code here:
        jCheckBoxTipoCoche.setSelected(false);
        jCheckBoxTipoCoche.setEnabled(true);
        jCheckBoxTipoMoto.setSelected(false);
        jCheckBoxTipoMoto.setEnabled(true);
        jCheckBoxTipoCamion.setEnabled(true);
        jCheckBoxTipoCamion.setSelected(true);
        jCheckBoxAddRemolque.setSelected(false);
        jCheckBoxAddRemolque.setEnabled(true);
        jCheckBoxAddCapota.setSelected(false);
        jCheckBoxAddCapota.setEnabled(false);
        jCheckBoxAddSidecar.setSelected(false);
        jCheckBoxAddSidecar.setEnabled(false);
        
        tipoVehiculo = "Camion";
    }//GEN-LAST:event_jCheckBoxTipoCamionActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
     nombreVehiculo = jTextNombre.getText();
     nombreModelo = jTextModelo.getText();
     yearVehiculo = jTextYear.getText();
        
     finalMessage = "Nombre del Vehiculo: " + nombreVehiculo + "\n" +
                        "Nombre del Modelo: " + nombreModelo + "\n" +
                        "Año del Vehiculo: " + yearVehiculo;   
        
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jCheckBoxTipoCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTipoCocheActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxTipoCoche.isSelected()) {
            jCheckBoxTipoCoche.setSelected(true);
            jCheckBoxTipoMoto.setSelected(false);
            jCheckBoxTipoMoto.setEnabled(true);
            jCheckBoxTipoCamion.setEnabled(true);
            jCheckBoxTipoCamion.setSelected(false);
            jCheckBoxAddRemolque.setSelected(false);
            jCheckBoxAddRemolque.setEnabled(false);
            jCheckBoxAddCapota.setSelected(false);
            jCheckBoxAddCapota.setEnabled(true);
            jCheckBoxAddSidecar.setSelected(false);
            jCheckBoxAddSidecar.setEnabled(false);
            
            tipoVehiculo = "Coche";
            
        } else {
            jCheckBoxTipoCoche.setSelected(false);
            tipoVehiculo = "";
        }
        
    }//GEN-LAST:event_jCheckBoxTipoCocheActionPerformed

    private void jCheckBoxTipoMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTipoMotoActionPerformed
        // TODO add your handling code here:
        jCheckBoxTipoCoche.setSelected(false);
        jCheckBoxTipoCoche.setEnabled(true);
        jCheckBoxTipoMoto.setSelected(true);
        jCheckBoxTipoMoto.setEnabled(true);
        jCheckBoxTipoCamion.setEnabled(true);
        jCheckBoxTipoCamion.setSelected(false);
        jCheckBoxAddRemolque.setSelected(false);
        jCheckBoxAddRemolque.setEnabled(false);
        jCheckBoxAddCapota.setSelected(false);
        jCheckBoxAddCapota.setEnabled(false);
        jCheckBoxAddSidecar.setSelected(false);
        jCheckBoxAddSidecar.setEnabled(true);
        
        tipoVehiculo = "Moto";
    }//GEN-LAST:event_jCheckBoxTipoMotoActionPerformed

    private void jRadioButtonGasGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGasGasolinaActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonGasGasolina.isSelected())
            tipoCombustible = "Gasolina";
    }//GEN-LAST:event_jRadioButtonGasGasolinaActionPerformed

    private void jRadioButtonGasDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGasDieselActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonGasDiesel.isSelected()) {
            tipoCombustible = "Diesel";
        }
    }//GEN-LAST:event_jRadioButtonGasDieselActionPerformed

    private void jRadioButtonGasElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGasElectricoActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonGasElectrico.isSelected()) {
            tipoCombustible = "Electrico";
        }
    }//GEN-LAST:event_jRadioButtonGasElectricoActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jCheckBoxTipoCoche.setSelected(false);
        jCheckBoxTipoCoche.setEnabled(true);
        jCheckBoxTipoMoto.setSelected(false);
        jCheckBoxTipoMoto.setEnabled(true);
        jCheckBoxTipoCamion.setEnabled(true);
        jCheckBoxTipoCamion.setSelected(false);
        jCheckBoxAddRemolque.setSelected(false);
        jCheckBoxAddRemolque.setEnabled(true);
        jCheckBoxAddCapota.setSelected(false);
        jCheckBoxAddCapota.setEnabled(true);
        jCheckBoxAddSidecar.setSelected(false);
        jCheckBoxAddSidecar.setEnabled(true);
        
        finalMessage = "";
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jCheckBoxAddRemolqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAddRemolqueActionPerformed
        // TODO add your handling code here:
        jCheckBoxTipoCoche.setSelected(false);
        jCheckBoxTipoCoche.setEnabled(true);
        jCheckBoxTipoMoto.setSelected(false);
        jCheckBoxTipoMoto.setEnabled(true);
        jCheckBoxTipoCamion.setEnabled(true);
        jCheckBoxTipoCamion.setSelected(true);
        jCheckBoxAddRemolque.setSelected(true);
        jCheckBoxAddRemolque.setEnabled(true);
        jCheckBoxAddCapota.setSelected(false);
        jCheckBoxAddCapota.setEnabled(false);
        jCheckBoxAddSidecar.setSelected(false);
        jCheckBoxAddSidecar.setEnabled(false);
        
        tipoAdd = "Remolque";
    }//GEN-LAST:event_jCheckBoxAddRemolqueActionPerformed

    private void jCheckBoxAddCapotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAddCapotaActionPerformed
        // TODO add your handling code here:
        jCheckBoxTipoCoche.setSelected(true);
        jCheckBoxTipoMoto.setSelected(false);
        jCheckBoxTipoMoto.setEnabled(true);
        jCheckBoxTipoCamion.setEnabled(true);
        jCheckBoxTipoCamion.setSelected(false);
        jCheckBoxAddRemolque.setSelected(false);
        jCheckBoxAddRemolque.setEnabled(false);
        jCheckBoxAddCapota.setSelected(true);
        jCheckBoxAddCapota.setEnabled(true);
        jCheckBoxAddSidecar.setSelected(false);
        jCheckBoxAddSidecar.setEnabled(false);
        
        tipoAdd = "Capota";
    }//GEN-LAST:event_jCheckBoxAddCapotaActionPerformed

    private void jCheckBoxAddSidecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAddSidecarActionPerformed
        // TODO add your handling code here:
         jCheckBoxTipoCoche.setSelected(false);
        jCheckBoxTipoCoche.setEnabled(true);
        jCheckBoxTipoMoto.setSelected(true);
        jCheckBoxTipoMoto.setEnabled(true);
        jCheckBoxTipoCamion.setEnabled(true);
        jCheckBoxTipoCamion.setSelected(false);
        jCheckBoxAddRemolque.setSelected(false);
        jCheckBoxAddRemolque.setEnabled(false);
        jCheckBoxAddCapota.setSelected(false);
        jCheckBoxAddCapota.setEnabled(false);
        jCheckBoxAddSidecar.setSelected(true);
        jCheckBoxAddSidecar.setEnabled(true);
    }//GEN-LAST:event_jCheckBoxAddSidecarActionPerformed

    private void jComboBoxColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColorsActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jComboBoxColorsActionPerformed

    private void jButtonRemoveVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveVehiculoActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tablaVehiculos = (DefaultTableModel) jTableMarcaModelo.getModel();
        int selectedRow = jTableMarcaModelo.getSelectedRow();
        tablaVehiculos.removeRow(selectedRow);
        
        
    }//GEN-LAST:event_jButtonRemoveVehiculoActionPerformed

    private void jButtonAddVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVehiculoActionPerformed
        // TODO add your handling code here:ç
        String nombreVehiculo = jTextNombre.getText();
        String nombreModelo = jTextModelo.getText();
        
        int choice = JOptionPane.showConfirmDialog(this, "Do you want to add the vehicle?","Accept",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        
        if(choice == JOptionPane.YES_OPTION) {
            if(!nombreVehiculo.isEmpty() || !nombreModelo.isEmpty()) {
                DefaultTableModel tablaVehiculos = (DefaultTableModel) jTableMarcaModelo.getModel();
                tablaVehiculos.addRow(new Object[]{nombreVehiculo,nombreModelo});
            }
        }else {
            JOptionPane.showMessageDialog(this, "El vehiculo o el modelo esta vacio");
        }  
    }//GEN-LAST:event_jButtonAddVehiculoActionPerformed

    private void jTextModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextModeloActionPerformed
        // TODO add your handling code here:
        nombreModelo = jTextModelo.getText();
    }//GEN-LAST:event_jTextModeloActionPerformed

    private void jTextYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextYearActionPerformed
        // TODO add your handling code here:
        yearVehiculo = jTextYear.getText();
    }//GEN-LAST:event_jTextYearActionPerformed

    private void jMenuCamionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCamionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCamionMouseClicked

    private void jMenuCamionMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCamionMensajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCamionMensajeMouseClicked

    private void jMenuMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMotoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMotoMouseClicked

    private void jMenuMotoMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMotoMensajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMotoMensajeMouseClicked

    private void jMenuCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCocheActionPerformed

    private void jMenuCocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCocheMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCocheMouseClicked

    private void jMenuCocheMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCocheMensajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCocheMensajeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonAddVehiculo;
    private javax.swing.JButton jButtonRemoveVehiculo;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JCheckBox jCheckBoxAddCapota;
    private javax.swing.JCheckBox jCheckBoxAddRemolque;
    private javax.swing.JCheckBox jCheckBoxAddSidecar;
    private javax.swing.JCheckBox jCheckBoxTipoCamion;
    private javax.swing.JCheckBox jCheckBoxTipoCoche;
    private javax.swing.JCheckBox jCheckBoxTipoMoto;
    private javax.swing.JComboBox<String> jComboBoxColors;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelCombustible;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarCoches;
    private javax.swing.JMenu jMenuCamion;
    private javax.swing.JMenu jMenuCamionMensaje;
    private javax.swing.JMenu jMenuCoche;
    private javax.swing.JMenu jMenuCocheMensaje;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuMoto;
    private javax.swing.JMenu jMenuMotoMensaje;
    private javax.swing.JRadioButton jRadioButtonGasDiesel;
    private javax.swing.JRadioButton jRadioButtonGasElectrico;
    private javax.swing.JRadioButton jRadioButtonGasGasolina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMarcaModelo;
    private javax.swing.JTextField jTextModelo;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextYear;
    // End of variables declaration//GEN-END:variables
}
